#+title: Conway Castle
#+subtitle:
#+date: <2020-08-06 Thu>
#+categories[]: places
#+tags[]: castles, conway, conwy 
#+image:
#+small_image:
#+OPTIONS: toc:nil 

*** History
The castle at the mouth of the Conwy river was built in the late 13th century as part of Edward I's fortification of Wales. It was built to replace the castle built by Edward's father on the high ground on the opposite bank of the river at Deganwy. As with many of his castles, Edward chose ease of resupply by sea over the tactical advantages of occupying the high ground - siege was an effective, if expensive, tactic when dealing with fortified positions. The castle has eight towers and a postern gate opening on the river for the landing of supplies. The castle has eight imposing towers and a postern gate opening onto the river for the landing of supplies.

Through its positioning, Conwy castle commands the river conwy estuary and provided as strong focus and base of operations at the northern edge of the troublesome Snowdonia region.

Soon after it had been completed, the castle was besieged by Madog ap Llywelyn, and was taken and held for a short time by Owain Glynd&wcirc;r in 1401. 

During the English civil war, the castle was held by forces loyal to the crown. Though the castle did not fall during the war, at the end the garrison surrendered to the parliamentary forces who later partly destroyed the structure, leaving it largely as it is today.

*** Folklore    
Like many castles, Conwy castle is said to have its fair share of ghostly phenomena. There have been reports of dark figures on the battlements and similar figures appear in some of the windows. Visitors have also reported feelings of terror or dread in certain locations within the castle, though this might have something to do with the precipitous castle walls. 


*** Facilities
The castle has an easily-accessed visitors' centre and gift shop which is well worth a visit, while the town of Conwy, though small, has a plethora of arts, crafts, and gift shops. There is also Conwy harbour, built below the castle and the site of the smallest house in Wales.


*** Visiting
[Map](/places/maps/wales/)


Conwy can be approached from the north, south or from the beautiful Conwy valley. The A56 from Chester passes under the river and the town; the junctions each side of the river lead to the town. The northern approach leads the visitor across the river and provides excellent views of the castle. Approaching from the south, one first encounters the town walls. A one-way system helps traffic flow, guiding the traffic towards the river and a splendid view of the castle at the top end of a rather straight street lined by small shops and pubs.

Parking can be tricky. There is a limited, and usually full, car-parking area on the quay-side, and a larger, more accessible one behind the main street reached by turning left at the roundabout immediately after passing the castle (if approaching from the north). There is a narrow arch, part of the town's walls, which is wide enough for one vehicle - pay attention to the rights of way.

Within Conwy and the surrounding areas, there is a wide choice of accommodation from hotels and guest houses to chalet and caravan parks.
 
